# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f612f03b2134d83a01d455df4e38d658d498dddab303303345b89ea32e97f7130efd2a9fbce79a3942d57424391bba0677827d775c08658d6860cb081dacd12b

test:
  secret_key_base: 1b199770053641c57933bfd8cf01744ff72ef7d30db68eb5f90e31200a4634189ec6d0b5edc8f543fe4968bc5de0f093f3cf1c6c46a75c208f67ca326f0b3216

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
